### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by litQp** [UNICT-Fake-Audio/fake-audio-detector#8]
PS C:\Users\valera\Desktop\python\fake-audio-detector> python main.py "C:\Users\valera\Desktop\python\tortoise-tts\examples\favorites\daniel_craig_training_ethics.mp3"
The 'duration' characteristic is missing.
The 'spectrum' characteristic is missing.
The 'mean_frequency' characteristic is missing.
The 'peak_frequency' characteristic is missing.
The 'frequencies_std' characteristic is missing.
Characteristic 'amplitudes_cum_sum' is missing.
The 'mode_frequency' characteristic is missing.
The 'median_frequency' characteristic is missing.
The characteristic 'frequencies_q25' is missing.
The characteristic 'frequencies_q75' is missing.
The 'iqr' characteristic is missing.
The 'freqs_skewness' characteristic is missing.
The 'freqs_kurtosis' characteristic is missing.
The 'spectral_bandwidth' characteristic is missing.
There is no 'energy' characteristic.
There is no 'rms' characteristic.
The 'zcr' characteristic is missing.
The 'meanfun' characteristic is missing.
The 'minfun' characteristic is missing.
The 'maxfun' characteristic is missing.
The 'meandom' characteristic is missing.
The 'mindom' characteristic is missing.
The 'maxdom' characteristic is missing.
The 'dfrange' characteristic is missing.
The 'modindex' characteristic is missing.
An error occurred with feature imfcc: unsupported operand type(s) for -: 'NoneType' and 'float'
C:\Users\valera\AppData\Local\Programs\Python\Python312\Lib\site-packages\scikit_learn-1.4.2-py3.12-win-amd64.egg\sklearn\base.py:376: InconsistentVersionWarning: Trying to unpickle estimator DecisionTreeClassifier from version 1.0.1 when using version 1.4.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\valera\Desktop\python\fake-audio-detector\main.py", line 9, in <module>
    model = joblib.load(MODEL)
            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\valera\AppData\Local\Programs\Python\Python312\Lib\site-packages\joblib-1.4.0-py3.12.egg\joblib\numpy_pickle.py", line 658, in load
    obj = _unpickle(fobj, filename, mmap_mode)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\valera\AppData\Local\Programs\Python\Python312\Lib\site-packages\joblib-1.4.0-py3.12.egg\joblib\numpy_pickle.py", line 577, in _unpickle
    obj = unpickler.load()
          ^^^^^^^^^^^^^^^^
  File "C:\Users\valera\AppData\Local\Programs\Python\Python312\Lib\pickle.py", line 1205, in load
    dispatch[key[0]](self)
  File "C:\Users\valera\AppData\Local\Programs\Python\Python312\Lib\pickle.py", line 1530, in load_stack_global
    self.append(self.find_class(module, name))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\valera\AppData\Local\Programs\Python\Python312\Lib\pickle.py", line 1572, in find_class
    __import__(module, level=0)
ModuleNotFoundError: No module named 'dill'

**Comment by Helias** [comment]
`ModuleNotFoundError: No module named 'dill'`

I think you are missing some python libraries, did you run `pip3 install -r requirements.txt` ?

**Comment by Helias** [comment]
I have updated the script, it should work as expected now.
I've also added the `dill` module in the requirements.txt
