### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by kaworururur** [UNICT-Fake-Audio/fake-audio-detector#9]
I don't know why, but no matter what audio I upload like data, I have this error (duration). Can you help me? I downloaded requirements.txt

C:\Users\24\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
C:\Users\24\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\spafe\features\spfeats.py:89: RuntimeWarning: invalid value encountered in scalar divide
  sk = np.sum(magnitude_spectrum * (freqs - mu1)  3) / (
C:\Users\24\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\spafe\features\spfeats.py:122: RuntimeWarning: invalid value encountered in scalar divide
  sk = np.sum(magnitude_spectrum * (freqs - mu1)  4) / (
C:\Users\24\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\spafe\features\spfeats.py:152: RuntimeWarning: divide by zero encountered in log
  * np.sum(magnitude_spectrum * np.log(magnitude_spectrum))
C:\Users\24\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\spafe\features\spfeats.py:152: RuntimeWarning: invalid value encountered in multiply
  * np.sum(magnitude_spectrum * np.log(magnitude_spectrum))
Traceback (most recent call last):
  File "D:\lian3\main.py", line 8, in <module>
    sample_features = get_all_features_from_sample(FILE_PATH)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\lian3\shared\feature_extraction.py", line 63, in get_all_features_from_sample
    sp_feats = extract_sp_feats(file_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\lian3\shared\feature_extraction.py", line 25, in extract_sp_feats
    sp_feat_type = type(sp_feats[sp_feat_name])
                        ~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'duration'

**Comment by Helias** [comment]
I have updated the script, it should work as expected now
